### ISSUE TITLE
Help with multi-user debugging

### ISSUE THREAD

**Issue by TonyChen-SH** [mougrim/php-xdebug-proxy#10]
```
[2018-11-03 11:49:47] xdebug-proxy.NOTICE: [Proxy][IdeRegistration] Listening for new connections on '0.0.0.0:9001'... array ( ) array ( )
[2018-11-03 11:49:47] xdebug-proxy.NOTICE: [Proxy][Xdebug] Listening for new connections on '0.0.0.0:9008'... array ( ) array ( )
[2018-11-03 11:50:06] xdebug-proxy.NOTICE: [IdeRegistration] Accepted connection. array (   'ide' => '127.0.0.1:61703', ) array ( )
[2018-11-03 11:50:06] xdebug-proxy.NOTICE: [IdeRegistration] Process request from IDE. array (   'ide' => '127.0.0.1:61703',   'request' => 'proxyinit -p 9001 -k WENXIN_MALL -m 1', ) array ( )
[2018-11-03 11:50:06] xdebug-proxy.WARNING: [IdeRegistration] Skip unsupported arguments. array (   'ide' => '127.0.0.1:61703',   'request' => 'proxyinit -p 9001 -k WENXIN_MALL -m 1',   'command' => 'proxyinit',   'unsupportedArguments' =>    array (     2 => '-m',   ), ) array ( )
[2018-11-03 11:50:06] xdebug-proxy.NOTICE: [IdeRegistration] Add new ide '127.0.0.1:9001' array (   'ide' => '127.0.0.1:9001',   'request' => 'proxyinit -p 9001 -k WENXIN_MALL -m 1',   'command' => 'proxyinit',   'key' => 'WENXIN_MALL', ) array ( )
[2018-11-03 11:50:06] xdebug-proxy.NOTICE: [IdeRegistration] Send response. array (   'ide' => '127.0.0.1:61703',   'response' => '<?xml version="1.0" encoding="UTF-8"?> <proxyinit success="1" idekey="WENXIN_MALL" address="127.0.0.1" port="9001"/> ', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.NOTICE: [IdeRegistration] Accepted connection. array (   'ide' => '127.0.0.1:61708', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.ERROR: [IdeRegistration] Invalid request from IDE. array (   'ide' => '127.0.0.1:61708',   'request' => '519', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.NOTICE: [IdeRegistration] Process request from IDE. array (   'ide' => '127.0.0.1:61708',   'request' => '<?xml version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/index.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="87752" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.ERROR: Can't parse argument version="1.0" array (   'arguments' => 'version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/index.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="87752" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.ERROR: Can't parse argument encoding="iso-8859-1"?> <init array (   'arguments' => 'version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/index.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="87752" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.ERROR: Can't parse argument xmlns="urn:debugger_protocol_v1" array (   'arguments' => 'version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/index.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="87752" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.ERROR: Can't parse argument xmlns:xdebug="http://xdebug.org/dbgp/xdebug" array (   'arguments' => 'version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/index.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="87752" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.ERROR: Can't parse argument fileuri="file:///Users/chendan/Project/work-wenxing/mall/index.php" array (   'arguments' => 'version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/index.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="87752" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.ERROR: Can't parse argument language="PHP" array (   'arguments' => 'version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/index.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="87752" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.ERROR: Can't parse argument xdebug:language_version="7.2.10" array (   'arguments' => 'version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/index.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="87752" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.ERROR: Can't parse argument protocol_version="1.0" array (   'arguments' => 'version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/index.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="87752" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.ERROR: Can't parse argument appid="87752" array (   'arguments' => 'version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/index.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="87752" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.ERROR: Can't parse argument idekey="WENXIN_MALL"><engine array (   'arguments' => 'version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/index.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="87752" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.ERROR: Can't parse argument version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick array (   'arguments' => 'version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/index.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="87752" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.ERROR: Can't parse argument Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright array (   'arguments' => 'version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/index.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="87752" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.ERROR: Can't parse argument (c) array (   'arguments' => 'version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/index.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="87752" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.ERROR: Can't parse argument 2002-2018 array (   'arguments' => 'version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/index.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="87752" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.ERROR: Can't parse argument by array (   'arguments' => 'version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/index.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="87752" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.ERROR: Can't parse argument Derick array (   'arguments' => 'version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/index.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="87752" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.ERROR: Can't parse argument Rethans]]></copyright></init> array (   'arguments' => 'version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/index.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="87752" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.ERROR: [IdeRegistration] Unknown command from IDE. array (   'ide' => '127.0.0.1:61708',   'request' => '<?xml version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/index.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="87752" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>',   'command' => '<?xml', ) array ( )
[2018-11-03 11:50:12] xdebug-proxy.NOTICE: [IdeRegistration] Send response. array (   'ide' => '127.0.0.1:61708',   'response' => '<?xml version="1.0" encoding="UTF-8"?> <proxyerror success="0"><error id="1"><message>Unknown command \'&lt;?xml\'</message></error></proxyerror> ', ) array ( )
```
What did I do wrong?

**Comment by mougrim** [comment]
Hi, @TonyChen-SH.
Looks like you try to connect to ide-registration port 9001 form xdebug.
But according logs xdebug connections accepted on 9008. Try use it, something like this:
```php
php -d'xdebug.remote_autostart=On' -d'xdebug.idekey=WENXIN_MALL' -d'xdebug.remote_connect_back=On' -d'xdebug.remote_enable=On' -d'xdebug.remote_host=127.0.0.1' -d'xdebug.remote_port=9008' /Users/chendan/Project/work-wenxing/mall/index.php
```

**Comment by TonyChen-SH** [comment]
now, I have a central server. phpstorm register on it.  but proxy not working....
```
Using config path /root/xdebug-proxy-integration/config
[2018-11-10 10:24:32] xdebug-proxy.NOTICE: [Proxy][IdeRegistration] Listening for new connections on '0.0.0.0:9001'... array ( ) array ( )
[2018-11-10 10:24:32] xdebug-proxy.NOTICE: [Proxy][Xdebug] Listening for new connections on '0.0.0.0:9008'... array ( ) array ( )
[2018-11-10 10:24:36] xdebug-proxy.NOTICE: [IdeRegistration] Accepted connection. array (   'ide' => '116.*.*.224:49261', ) array ( )
[2018-11-10 10:24:36] xdebug-proxy.NOTICE: [IdeRegistration] Process request from IDE. array (   'ide' => '116.*.*.224:49261',   'request' => 'proxyinit -p 9008 -k WENXIN_MALL -m 1', ) array ( )
[2018-11-10 10:24:36] xdebug-proxy.WARNING: [IdeRegistration] Skip unsupported arguments. array (   'ide' => '116.*.*.224:49261',   'request' => 'proxyinit -p 9008 -k WENXIN_MALL -m 1',   'command' => 'proxyinit',   'unsupportedArguments' =>    array (     2 => '-m',   ), ) array ( )
[2018-11-10 10:24:36] xdebug-proxy.NOTICE: [IdeRegistration] Add new ide '116.*.*.224:9008' array (   'ide' => '116.*.*.224:9008',   'request' => 'proxyinit -p 9008 -k WENXIN_MALL -m 1',   'command' => 'proxyinit',   'key' => 'WENXIN_MALL', ) array ( )
[2018-11-10 10:24:36] xdebug-proxy.NOTICE: [IdeRegistration] Send response. array (   'ide' => '116.*.*.224:49261',   'response' => '<?xml version="1.0" encoding="UTF-8"?> <proxyinit success="1" idekey="WENXIN_MALL" address="116.*.*.224" port="9008"/> ', ) array ( )
[2018-11-10 10:24:42] xdebug-proxy.INFO: [Xdebug] Accepted connection array (   'xdebug' => '116.*.*.224:49267', ) array ( )
[2018-11-10 10:24:42] xdebug-proxy.INFO: Process request array (   'xdebug' => '116.*.*.224:49267',   'request' => '<?xml version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/.router.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="22528" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>',   'requestLength' => '521', ) array ( )
[2018-11-10 10:24:42] xdebug-proxy.NOTICE: [Xdebug][Ide][Init] Try to init connect to ide. array (   'xdebug' => '116.*.*.224:49267',   'request' => '<?xml version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/.router.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="22528" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>',   'ideKey' => 'WENXIN_MALL',   'ide' => '116.*.*.224:9008', ) array ( )
[2018-11-10 10:24:52] xdebug-proxy.ERROR: [Xdebug] Can't connect to ide: Amp\Socket\ConnectException: Connecting to tcp://116.*.*.224:9008 failed: timeout exceeded (10000 ms) in /root/xdebug-proxy-integration/vendor/amphp/socket/src/functions.php:134 Stack trace: #0 [internal function]: Amp\Socket\{closure}() #1 /root/xdebug-proxy-integration/vendor/amphp/amp/lib/Coroutine.php(71): Generator->throw(Object(Amp\TimeoutException)) #2 /root/xdebug-proxy-integration/vendor/amphp/amp/lib/Failure.php(26): Amp\Coroutine->Amp\{closure}(Object(Amp\TimeoutException), NULL) #3 /root/xdebug-proxy-integration/vendor/amphp/amp/lib/Internal/Placeholder.php(122): Amp\Failure->onResolve(Object(Closure)) #4 /root/xdebug-proxy-integration/vendor/amphp/amp/lib/Internal/Placeholder.php(151): class@anonymous->resolve(Object(Amp\Failure)) #5 /root/xdebug-proxy-integration/vendor/amphp/amp/lib/Deferred.php(50): class@anonymous->fail(Object(Amp\TimeoutException)) #6 /root/xdebug-proxy-integration/vendor/amphp/amp/lib/functions.php(201): Amp\Deferred->fail(Object(Amp\TimeoutException)) #7 /root/xdebug-proxy-integration/vendor/amphp/amp/lib/Loop/NativeDriver.php(101): Amp\Promise\{closure}('l', NULL) #8 /root/xdebug-proxy-integration/vendor/amphp/amp/lib/Loop/Driver.php(130): Amp\Loop\NativeDriver->dispatch(true) #9 /root/xdebug-proxy-integration/vendor/amphp/amp/lib/Loop/Driver.php(70): Amp\Loop\Driver->tick() #10 /root/xdebug-proxy-integration/vendor/amphp/amp/lib/Loop.php(76): Amp\Loop\Driver->run() #11 /root/xdebug-proxy-integration/vendor/mougrim/php-xdebug-proxy/src/Proxy.php(45): Amp\Loop::run() #12 /root/xdebug-proxy-integration/vendor/mougrim/php-xdebug-proxy/src/Runner.php(58): Mougrim\XdebugProxy\Proxy->run() #13 /root/xdebug-proxy-integration/vendor/mougrim/php-xdebug-proxy/bin/xdebug-proxy(35): Mougrim\XdebugProxy\Runner->run() #14 {main} array (   'xdebug' => '116.*.*.224:49267',   'request' => '<?xml version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/.router.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="22528" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>',   'ideKey' => 'WENXIN_MALL',   'ide' => '116.*.*.224:9008', ) array ( )
```

**Comment by mougrim** [comment]
Hi, @TonyChen-SH!
Could you give more details?
'116.*.*.224' - was it real ip and you mask it?
I don't need real ips, but I need understand what machines do you use.
Are machine with ide, machine with proxy and machine, where you debug php - same machines?
According logs you registered ide as 116.*.*.224:9008 and proxy can't connect to it. Is IDE listens to it?

**Comment by TonyChen-SH** [comment]
I drew a picture of what I wanted. very machine is alone. i want build a central proxy server.  php xdebug connect to proxy server and phpstorm register on it. now, proxy server allocates the xdebug request.


![proxy](https://user-images.githubusercontent.com/27392605/48323787-d0de0a80-e668-11e8-8845-a53b8f4e8ad3.png)

**Comment by mougrim** [comment]
@TonyChen-SH

Let's look example:
- server with php and xdebug on 116.1.1.223. It have next in php.ini:
```ini
xdebug.remote_autostart=On
xdebug.remote_connect_back=On
xdebug.remote_enable=On
xdebug.remote_host=116.1.1.223
xdebug.remote_port=9008
```
- xdebug-proxy-server with xdebug proxy on 116.1.1.224:9008 and registration 116.1.1.224:9001
- user with laptop on 116.1.1.225 and accept xdebug-connections on 9000 port.

1. User register ide in proxy using 116.1.1.224:9001, there should next row in logs:
```
[2018-11-10 10:24:36] xdebug-proxy.NOTICE: [IdeRegistration] Add new ide '116.1.1.225:9000' array (   'ide' => '116.1.1.225:9000',   'request' => 'proxyinit -p 9000 -k WENXIN_MALL -m 1',   'command' => 'proxyinit',   'key' => 'WENXIN_MALL', ) array ( )
```
2. User go to [http://url.com/login?XDEBUG_SESSION_START=WENXIN_MALL](http://url.com/login?XDEBUG_SESSION_START=WENXIN_MALL), where url.com is 116.1.1.223.

3. When server accept connection, it should connect to xdebug-proxy-server, there should be next in logs:
```
[2018-11-10 10:24:42] xdebug-proxy.INFO: [Xdebug] Accepted connection array (   'xdebug' => '116.1.1.223:49267', ) array ( )
[2018-11-10 10:24:42] xdebug-proxy.NOTICE: [Xdebug][Ide][Init] Try to init connect to ide. array (   'xdebug' => '116.1.1.223:49267',   'request' => '<?xml version="1.0" encoding="iso-8859-1"?> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Users/chendan/Project/work-wenxing/mall/.router.php" language="PHP" xdebug:language_version="7.2.10" protocol_version="1.0" appid="22528" idekey="WENXIN_MALL"><engine version="2.6.1"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2018 by Derick Rethans]]></copyright></init>',   'ideKey' => 'WENXIN_MALL',   'ide' => '116.1.1.225:9000', ) array ( )
```

But according your logs I see that proxy try to connect to 116.1.1.224:9008 instead of 116.1.1.225:9000 (in my example).
Maybe proxy and ide in your case are in one port. Could you check it?

**Comment by mougrim** [comment]
Hey, @TonyChen-SH.
Is problem still actual?

**Comment by mougrim** [comment]
No answer for long time, so close issue.
