### ISSUE TITLE
Changes in grumphp and bad composer.lock

### ISSUE THREAD

**Issue by aleixq** [mougrim/php-xdebug-proxy#25]
Trying to run this project  it returns:

```
php-xdebug-proxy$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - phpro/grumphp is locked to version v0.14.3 and an update of this package was not requested.
    - phpro/grumphp v0.14.3 requires composer-plugin-api ~1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint. 
```

I need to remove composer.lock and run composer install again.
Then it continues but it complains about grumphp.yml:

```
PHP Fatal error:  Uncaught GrumPHP\Exception\DeprecatedException: Direct configuration of parameter hooks_dir is not allowed anymore.                                                                                                                                         
Please rename the `parameters` section in your grumphp.yaml file to `grumphp`.                                                                                                                                                                   
More info: https://github.com/phpro/grumphp/releases/tag/v0.19.0              
                                                                                                                                                      
 in /usr/local/src/php-xdebug-proxy/vendor/phpro/grumphp/src/Exception/DeprecatedException.php:11                                               
Stack trace:                                                                                                                                   
#0 /usr/local/src/php-xdebug-proxy/vendor/phpro/grumphp/src/Configuration/GrumPHPExtension.php(40): GrumPHP\Exception\DeprecatedException::directParameterConfiguration()  
#1 /usr/local/src/php-xdebug-proxy/vendor/phpro/grumphp/src/Configuration/GrumPHPExtension.php(17): GrumPHP\Configuration\GrumPHPExtension->loadInternal()
#2 /usr/local/src/php-xdebug-proxy/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(76): GrumPHP\Configuration\GrumPHPExtension->load()
#3 /usr/local/src/php-xdebug-proxy/vendor/symfony/dependency-injection/Compiler/Compiler.php(91): Symfony\Component\DependencyInjection\Compiler\MergeExtension in /usr/local/src/php-xdebug-proxy/vendor/phpro/grumphp/src/Exception/DeprecatedException.php on line 11
GrumPHP can not sniff your commits! (invalid-exit-code)                 
PHP Fatal error:  Uncaught GrumPHP\Exception\DeprecatedException: Direct configuration of parameter hooks_dir is not allowed anymore.
Please rename the `parameters` section in your grumphp.yaml file to `grumphp`.      
More info: https://github.com/phpro/grumphp/releases/tag/v0.19.0

 in /usr/local/src/php-xdebug-proxy/vendor/phpro/grumphp/src/Exception/DeprecatedException.php:11
Stack trace:
#0 /usr/local/src/php-xdebug-proxy/vendor/phpro/grumphp/src/Configuration/GrumPHPExtension.php(40): GrumPHP\Exception\DeprecatedException::directParameterConfiguration()
#1 /usr/local/src/php-xdebug-proxy/vendor/phpro/grumphp/src/Configuration/GrumPHPExtension.php(17): GrumPHP\Configuration\GrumPHPExtension->loadInternal()
#2 /usr/local/src/php-xdebug-proxy/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(76): GrumPHP\Configuration\GrumPHPExtension->load()
#3 /usr/local/src/php-xdebug-proxy/vendor/symfony/dependency-injection/Compiler/Compiler.php(91): Symfony\Component\DependencyInjection\Compiler\MergeExtension in /usr/local/src/php-xdebug-proxy/vendor/phpro/grumphp/src/Exception/DeprecatedException.php on line 11
GrumPHP can not sniff your commits! (invalid-exit-code)
```

Following the issue, there are breaking changes in grumphp since 0.16:  https://github.com/phpro/grumphp/pull/644

**Comment by mougrim** [comment]
Merged and released.
Thanks for PR!
