### ISSUE TITLE
Support for `-m` multi debugger option

### ISSUE THREAD

**Issue by bilogic** [mougrim/php-xdebug-proxy#39]
> -m | this tells the demon that the IDE supports (or doesn't) multiple debugger sessions. if -m is missing, zero or no support is 

https://xdebug.org/docs/dbgp

Possible to support this? I'm using PHP Tools from devsense and have trouble registering with this proxy. Logs below

```
[2022-12-24T12:47:06.799867+08:00] xdebug-proxy.NOTICE: [IdeRegistration] Accepted connection. array (   'ide' => '192.168.1.3:13520', ) array ( )
[2022-12-24T12:47:06.800074+08:00] xdebug-proxy.NOTICE: [IdeRegistration] Process request from IDE. array (   'ide' => '192.168.1.3:13520',   'request' => 'proxyinit -k dev1 -p 9000 -m 1', ) array ( )
[2022-12-24T12:47:06.800173+08:00] xdebug-proxy.WARNING: [IdeRegistration] Skip unsupported arguments. array (   'ide' => '192.168.1.3:13520',   'request' => 'proxyinit -k dev1 -p 9000 -m 1',   'command' => 'proxyinit',   'unsupportedArguments' =>    array (     2 => '-m',   ), ) array ( )
[2022-12-24T12:47:06.800232+08:00] xdebug-proxy.NOTICE: [IdeRegistration] Change ide from '192.168.1.3:9000' to '192.168.1.3:9000' array (   'ide' => '192.168.1.3:9000',   'request' => 'proxyinit -k dev1 -p 9000 -m 1',   'command' => 'proxyinit',   'key' => 'dev1', ) array ( )
[2022-12-24T12:47:06.800322+08:00] xdebug-proxy.NOTICE: [IdeRegistration] Send response. array (   'ide' => '192.168.1.3:13520',   'response' => '<?xml version="1.0" encoding="UTF-8"?> <proxyinit success="1" idekey="dev1" address="192.168.1.3" port="9000"/> ', ) array ( )
[2022-12-24T12:47:06.800460+08:00] xdebug-proxy.ERROR: [IdeRegistration] Can't write response to ide: Amp\ByteStream\ClosedException: The stream was closed by the peer in /xdebug/.config/composer/vendor/amphp/byte-stream/lib/ResourceOutputStream.php:196 Stack trace: #0 /xdebug/.config/composer/vendor/amphp/byte-stream/lib/ResourceOutputStream.php(171): Amp\ByteStream\ResourceOutputStream->send() #1 /xdebug/.config/composer/vendor/amphp/socket/src/Socket.php(74): Amp\ByteStream\ResourceOutputStream->end() #2 /xdebug/.config/composer/vendor/mougrim/php-xdebug-proxy/src/Handler/DefaultIdeHandler.php(263): Amp\Socket\Socket->end() #3 [internal function]: Mougrim\XdebugProxy\Handler\DefaultIdeHandler->handle() #4 /xdebug/.config/composer/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send() #5 /xdebug/.config/composer/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}() #6 /xdebug/.config/composer/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve() #7 /xdebug/.config/composer/vendor/amphp/byte-stream/lib/ResourceInputStream.php(109): Amp\Deferred->resolve() #8 /xdebug/.config/composer/vendor/amphp/amp/lib/Loop/Driver.php(119): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}() #9 /xdebug/.config/composer/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick() #10 /xdebug/.config/composer/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run() #11 /xdebug/.config/composer/vendor/mougrim/php-xdebug-proxy/src/Proxy.php(47): Amp\Loop::run() #12 /xdebug/.config/composer/vendor/mougrim/php-xdebug-proxy/src/Runner.php(65): Mougrim\XdebugProxy\Proxy->run() #13 /xdebug/.config/composer/vendor/mougrim/php-xdebug-proxy/bin/xdebug-proxy(35): Mougrim\XdebugProxy\Runner->run() #14 /xdebug/.config/composer/vendor/bin/xdebug-proxy(120): include('...') #15 {main} array (   'ide' => '192.168.1.3:13520',   'response' => '<?xml version="1.0" encoding="UTF-8"?> <proxyinit success="1" idekey="dev1" address="192.168.1.3" port="9000"/> ', ) array ( )
```

**Comment by mougrim** [comment]
Hey!
Php-xdebug-proxy just ignores this argument. How it should be processed?
Anyway, feel free, to create MR with implementing it.

> Can't write response to ide: Amp\ByteStream\ClosedException: The stream was closed by the peer

Looks like ide closes connection and doesn't wait response. I'm not sure, that it's correct behavior from IDE.

**Comment by bilogic** [comment]
The exception is still reproducible, but no longer an issue for me, see #38 for explanation. Thank you.
